### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by asdfxD** [SourceTurk/private-profile-game-hours#1]
Use latest SourceMod/Metamod/Steamworks.

L 01/02/2020 - 16:31:09: [SM] Blaming: gizli_profil.smx
L 01/02/2020 - 16:31:09: [SM] Call stack trace:
L 01/02/2020 - 16:31:09: [SM]   [0] SteamWorks_SetHTTPRequestContextValue
L 01/02/2020 - 16:31:09: [SM]   [1] Line 115, gizli_profil.sp::secretProfilControl
L 01/02/2020 - 16:31:09: [SM]   [2] Line 84, gizli_profil.sp::checkPlayerSecretProfil
L 01/02/2020 - 16:31:09: [SM]   [3] Line 25, gizli_profil.sp::OnClientPutInServer
L 01/02/2020 - 16:31:09: [SM] Exception reported: Invalid Handle 0 (error: 4)

**Comment by northeaster** [comment]
Will you try [version 1.2](https://github.com/SourceTurk/private-profile-game-hours/releases/tag/1.2) ?

**Comment by asdfxD** [comment]
It works. Is it possible to disable "Friendslist" check?

**Comment by northeaster** [comment]
See this resource. May not be possible.

[Steam_Web_API](https://developer.valvesoftware.com/wiki/Steam_Web_API)

**Comment by asdfxD** [comment]
Can't get it to work that players can join with following:

Profil Public
Game Public
Friends Private
Inventory Private

**Comment by northeaster** [comment]
Now that the error has resolved, create a new issue for this request.
